version: '2.0'

services:

# --------------------------------------------
 botmanager:
  build:
   context: ./botManager
  environment:
   - CONFIG=./config
   - CHANNEL=#test
   - ICON_URL=http://localhost/
   - CHART_URL=http://localhost:400
   - WEBTOKEN=
  volumes:
   - ./log/:/app/log/
   - ./config/:/app/config/

# --------------------------------------------
 crawler_btc:
  build:
   context: ./crawler
  env_file:
   - ./crawler.env
  environment:
   - CURRENCY=BTC
  volumes:
   - ./log/:/app/log/
   - ./config/:/app/config/

 crawler_eth:
  build:
   context: ./crawler
  env_file:
   - ./crawler.env
  environment:
   - CURRENCY=BTC
  volumes:
   - ./log/:/app/log/
   - ./config/:/app/config/

 crawler_xrp:
  build:
   context: ./crawler
  env_file:
   - ./crawler.env
  environment:
   - CURRENCY=XRP
  volumes:
   - ./log/:/app/log/
   - ./config/:/app/config/

 crawler_bch:
  build:
   context: ./crawler
  env_file:
   - ./crawler.env
  environment:
   - CURRENCY=BCH
  volumes:
   - ./log/:/app/log/
   - ./config/:/app/config/

 crawler_btg:
  build:
   context: ./crawler
  env_file:
   - ./crawler.env
  environment:
   - CURRENCY=BTG
  volumes:
   - ./log/:/app/log/
   - ./config/:/app/config/

# --------------------------------------------
 tracker_btc:
  build:
   context: ./tracker
  env_file:
   - ./tracker.env
  environment:
   - CURRENCY=BTC
   - PRICE_ROUND_RADIX=-3
  volumes:
   - ./log/:/app/log/
   - ./config/:/app/config/
   - ./chartData/btc/:/app/chartData/

 tracker_eth:
  build:
   context: ./tracker
  env_file:
   - ./tracker.env
  environment:
   - CURRENCY=ETH
   - PRICE_ROUND_RADIX=-1
  volumes:
   - ./log/:/app/log/
   - ./config/:/app/config/
   - ./chartData/eth/:/app/chartData/

 tracker_xrp:
  build:
   context: ./tracker
  env_file:
   - ./tracker.env
  environment:
   - CURRENCY=XRP
   - PRICE_ROUND_RADIX=0
  volumes:
   - ./log/:/app/log/
   - ./config/:/app/config/
   - ./chartData/xrp/:/app/chartData/

 tracker_bch:
  build:
   context: ./tracker
  env_file:
   - ./tracker.env
  environment:
   - CURRENCY=BCH
   - PRICE_ROUND_RADIX=-1
  volumes:
   - ./log/:/app/log/
   - ./config/:/app/config/
   - ./chartData/xrp/:/app/chartData/

 tracker_btg:
  build:
   context: ./tracker
  env_file:
   - ./tracker.env
  environment:
   - CURRENCY=BTG
   - PRICE_ROUND_RADIX=0
  volumes:
   - ./log/:/app/log/
   - ./config/:/app/config/
   - ./chartData/btg/:/app/chartData/

# --------------------------------------------
 chart_btc:
  build:
   context: ./chart
  ports:
   - "4000:3000"
  volumes:
   - ./chartData/btc/:/app/public/data

 chart_eth:
  build:
   context: ./chart
  ports:
   - "4002:3000"
  volumes:
   - ./chartData/eth/:/app/public/data/

 chart_xrp:
  build:
   context: ./chart
  ports:
   - "4001:3000"
  volumes:
   - ./chartData/xrp/:/app/public/data/

 chart_bch:
  build:
   context: ./chart
  ports:
   - "4003:3000"
  volumes:
   - ./chartData/bch/:/app/public/data/
